{
  "action": {
    "malware": {
      "result": [
        "Infiltrate",
        "Deploy payload",
        "Exfiltrate"
      ],
      "variety": [
        "Ransomware"
      ],
      "vector": [
        "Unknown"
      ]
    },
    "unknown": {
      "notes": "unknown action to gain initial foothold",
      "result": [
        "Infiltrate"
      ]
    }
  },
  "actor": {
    "external": {
      "country": [
        "Unknown"
      ],
      "motive": [
        "Financial"
      ],
      "name": [
        "Ragnar Locker"
      ],
      "region": [
        "000000"
      ],
      "variety": [
        "Organized crime"
      ]
    }
  },
  "asset": {
    "assets": [
      {
        "variety": "S - Unknown"
      }
    ],
    "cloud": [
      "Unknown"
    ],
    "role": [
      "IT"
    ]
  },
  "attribute": {
    "availability": {
      "variety": [
        "Obscuration"
      ]
    },
    "confidentiality": {
      "data": [
        {
          "variety": "Personal"
        }
      ],
      "data_disclosure": "Yes",
      "data_victim": [
        "Partner"
      ],
      "state": [
        "Stored"
      ]
    },
    "integrity": {
      "variety": [
        "Software installation"
      ]
    }
  },
  "confidence": "High",
  "discovery_method": {
    "external": {
      "variety": [
        "Actor disclosure"
      ]
    }
  },
  "incident_id": "221b00f0-0a06-11ed-84e4-4d6a8bbe6476",
  "plus": {
    "analysis_status": "Finalized",
    "analyst": "swidup",
    "asset_os": [
      "Unknown"
    ],
    "attribute": {
      "confidentiality": {
        "partner_data": "Yes"
      }
    },
    "created": "2022-07-23T04:34:57.663Z",
    "dbir_year": 2023,
    "event_chain": [
      {
        "action": "unk",
        "actor": "ext",
        "asset": "srv",
        "attribute": "unk",
        "summary": "Unknown action to gain initial access"
      },
      {
        "action": "mal",
        "actor": "ext",
        "asset": "srv",
        "attribute": "ia",
        "summary": "Ransomware installed"
      },
      {
        "action": "mal",
        "actor": "ext",
        "asset": "srv",
        "attribute": "cp",
        "summary": "Data copied"
      },
      {
        "action": "mal",
        "actor": "ext",
        "asset": "srv",
        "attribute": "au",
        "summary": "Encryption triggered"
      }
    ],
    "github": "18074",
    "master_id": "3befc1e6-91e3-44f7-8534-82bda7db17bc",
    "modified": "2022-07-23T05:37:20.685Z"
  },
  "reference": "https://krebsonsecurity.com/2021/09/customer-care-giant-ttec-hit-by-ransomware/",
  "schema_name": "vcdb",
  "schema_version": "1.4.0",
  "security_incident": "Confirmed",
  "source_id": "vcdb",
  "summary": "TTEC, a company used by some of the world\u2019s largest brands to help manage customer support and sales online and over the phone, is dealing with disruptions from a network security incident resulting from a ransomware attack.",
  "targeted": "Unknown",
  "timeline": {
    "incident": {
      "month": 8,
      "year": 2022
    }
  },
  "value_chain": {
    "cash-out": {
      "notes": "VERIS 1.3.6: value_chain.development.variety.Cryptocurrency added because action.malware.variety.Ransomware exists.",
      "variety": [
        "Cryptocurrency"
      ]
    },
    "development": {
      "variety": [
        "Ransomware"
      ]
    }
  },
  "victim": {
    "country": [
      "US"
    ],
    "employee_count": "50001 to 100000",
    "government": [
      "NA"
    ],
    "industry": "561422",
    "region": [
      "019021"
    ],
    "state": "CO",
    "victim_id": "TTEC"
  }
}